actor("chaplin").
athlete('ronaldo').
athlete('messi').
politician("ghandi").
politician("arnold").
politician(123).
actor("arnold").
athlete("arnold").

famous(X) :- actor(X); \
             athlete(X); \
             politician(X).

listing

famous(X)?


other(X) :- abc(X, "gual").
other(X) :- abc(X, "guali").
other(X) :- abc(X, "gual"). # This instruction will produce a warning

other(X) :- abc(X, "guali"); abc(X, "gual").

###########################

parent('john', 'damian').
parent('john', 'ellie').
parent('sarah', 'john').

grandparent(gp, gc) :- parent(gp, parent), parent(parent, gc).

sibling(X, Y) :- grandparent(Z, X), grandparent(Z, Y).

son(X, Y) :- parent(Y, X).

related(person, other) :- son(parent, other); parent(parent, other); sibling(parent, other).

related('sarah', anyone)?

