alpha("hello", "world").
beta(A, B) :- alpha(A, B).
charlie(900, 900).
delta(A, B) :- charlie(A, B).

beta(A, A)? # No
delta(A, B)? # A = 900, B = 900
delta(A, A)? # A = 900
delta(900, 900)? # Yes
delta(900, A)? # A = 900

abc(123).
abc(123)?

df1(1, 1).
df1(X, X)?

df2(1, 1).
df2(X, Y)?

df3(1, 2).
df3(X, X)?

df4(1, 2).
df4(X, Y)?


idf1(A, B) :- df1(A, B).
idf2(A, B) :- df2(A, B).
idf3(A, B) :- df3(A, B).
idf4(A, B) :- df4(A, B).

idf1(X, X)?
idf2(X, Y)?
idf3(X, X)?
idf4(X, Y)?
